# Generated by Django 3.2.4 on 2021-07-08 15:23

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.FileField(blank=True, upload_to=tweets.models.get_upload_path),
        ),
    ]
