# Generated by Django 3.2.4 on 2021-07-13 07:57

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ImageField(blank=True, default=None, upload_to=tweets.models.get_upload_path),
        ),
    ]
