# Generated by Django 3.2.4 on 2021-07-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_alter_tweet_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='media',
            new_name='image',
        ),
    ]
